### ISSUE TITLE
Error in Kodi V20

### ISSUE THREAD

**Issue by Shredder5262** [robweber/cronxbmc#28]
Hello - I have just installed Cron for Kodi on nexus and i get this error message in the logs. Can this addon be updated for nexus?

2023-02-18 12:14:58.535 T:31616   error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'AttributeError'>
                                                   Error Contents: module 'xbmc' has no attribute 'translatePath'
                                                   Traceback (most recent call last):
                                                     File "D:\Kodi\Kodi - V20 Nexus\portable_data\addons\service.cronxbmc\service.py", line 5, in <module>
                                                       CronService().runProgram()
                                                     File "D:\Kodi\Kodi - V20 Nexus\portable_data\addons\service.cronxbmc\resources\lib\cron\main.py", line 228, in __init__
                                                       self.manager = CronManager()
                                                     File "D:\Kodi\Kodi - V20 Nexus\portable_data\addons\service.cronxbmc\resources\lib\cron\main.py", line 34, in __init__
                                                       self.jobs = self._readCronFile()
                                                     File "D:\Kodi\Kodi - V20 Nexus\portable_data\addons\service.cronxbmc\resources\lib\cron\main.py", line 140, in _readCronFile
                                                       xbmcvfs.mkdir(xbmc.translatePath('special://profile/addon_data/service.cronxbmc/'))
                                                   AttributeError: module 'xbmc' has no attribute 'translatePath'
                                                   -->End of Python script error report<--

**Comment by robweber** [comment]
Thanks for pointing this out. The `translatePath` function was moved to the `xbmcvfs` module. With Nexus they must have finally deprecated the old function.

**Comment by TermeHansen** [comment]
Yes, just saw this as well on Nexus. And you are right, with Nexus that is deprecated. You did the change in the last refactor for getting it in main repo, but forgot it here in https://github.com/robweber/cronxbmc/blob/4ec63699baabf44367bc255e9665f4cd7f455e2a/resources/lib/cron/main.py#L140

should be:

`            xbmcvfs.mkdir(xbmcvfs.translatePath('special://profile/addon_data/service.cronxbmc/'))
`
I have tested on Nexus, and it is only that line...

**Comment by Shredder5262** [comment]
yep, that fixed it, thank you guys!

**Comment by TermeHansen** [comment]
@robweber should I make a PR to update this add-on for Nexus and also push to repo-scripts ?

**Comment by robweber** [comment]
I've been traveling for work this week. If you have time for a PR that would help. I can get it pushed to the repo after that. Thanks.

**Comment by robweber** [comment]
This is now awaiting merging into the Kodi repo - https://github.com/xbmc/repo-scripts/pull/2418
